"""
https://leetcode.com/problems/find-the-difference/
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter 
at a random position.
Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        count = {}
        for i in s:
            if i not in count:
                count[i] = 1
            else:
                count[i] += 1
        for i in t:
            if i not in count:
                return i
            else:
                count[i] -= 1
        for i in count.keys():
            if count[i] == -1:
                return i

print(Solution.findTheDifference(Solution(), s = "", t = "y"))
print(Solution.findTheDifference(Solution(), s = "abcd", t = "abcde"))
